services:
  source_postgres:
    image: postgres:9.2
    ports:
      - "5433:5432"
    networks:
      - elt_network
    env_file:
      - .env.source
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:9.2
    ports:
      - "5434:5432"
    networks:
      - elt_network
    env_file:
      - .env.destination

  elt_script:
    build:
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres

networks:
  elt_network:
    driver: bridge