services:
  source_postgres:
    image: postgres:9.2
    ports:
      - "5433:5432"
    networks:
      - elt_network
    env_file:
      - .env.source
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:9.2
    ports:
      - "5434:5432"
    networks:
      - elt_network
    env_file:
      - .env.destination

  elt_script:
    build:
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    command: [
      "run",
      "--profiles-dir",
      "/root",
      "--project-dir",
      "/dbt"
    ]
    networks:
      - elt_network
    volumes:
      - /custom_postgres:/dbt
      - ~/.dbt:/root
    depends_on:
      elt_script:
        condition: service_completed_successfully
    environment:
      DBT_PROFILE: default
      DBT_TARGET: dev

networks:
  elt_network:
    driver: bridge