version: '3'

services:
  source_postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - elt_network

    env_file:
      - .env.source
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    networks:
      - elt_network

    env_file:
      - .env.destination
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  elt_network:
    driver: bridge